apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-exchange-sc
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-data-exchange
  hostPath:
    path: /mnt/data/pv-data-exchange-sc
