---
- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ vector_install_dir }}"
    state: directory
    mode: '0755'

- name: Download Vector archive
  ansible.builtin.get_url:
    url: "{{ vector_download_url }}"
    dest: "/tmp/vector.tar.gz"

- name: Extract Vector archive
  ansible.builtin.unarchive:
    src: "/tmp/vector.tar.gz"
    dest: "{{ vector_install_dir }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: Ensure Vector config directory exists
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Vector config
  ansible.builtin.template:
    src: vector_config.j2
    dest: "{{ vector_config_dir }}/vector.toml"

- name: Launch Vector process
  ansible.builtin.shell: |
    nohup {{ vector_install_dir }}/bin/vector --config-toml {{ vector_config_dir }}/vector.toml \
      > /var/log/vector.log 2>&1 &
  args:
    executable: /bin/bash
  changed_when: false
