apiVersion: v1
kind: Service
metadata:
  name: multi-nginx-nodeport
spec:
  selector:
    app: multi-container
  ports:
  - name: nginx-nodeport
    port: 80
    targetPort: 80
    nodePort: 30100
  type: NodePort