apiVersion: v1
kind: Service
metadata:
  name: multi-service-clusterip
spec:
  selector:
    app: multi-container
  ports:
  - name: nginx-port
    port: 9001
    targetPort: 80
  - name: multitool-port
    port: 9002
    targetPort: 8080
  type: ClusterIP
