---
vector_version: "0.35.0"
vector_download_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
vector_install_dir: "/opt/vector"
vector_config_dir: "/etc/vector"
