---
- name: Download Vector archive
  ansible.builtin.get_url:
    url: "{{ vector_download_url }}"
    dest: "/tmp/vector.tar.gz"
    mode: '0644'

- name: Create installation directory
  ansible.builtin.file:
    path: "{{ vector_install_dir }}"
    state: directory
    mode: '0755'

- name: Extract Vector archive
  become: true
  ansible.builtin.unarchive:
    src: /tmp/vector.tar.gz
    dest: "{{ vector_install_dir }}"
    remote_src: yes
    extra_opts: ['--strip-components=1']

- name: Create symlink for vector binary
  become: true
  ansible.builtin.file:
    src: /opt/vector/vector-x86_64-unknown-linux-gnu/bin/vector
    dest: /usr/local/bin/vector
    state: link

- name: Create Vector config directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Vector config
  become: true
  ansible.builtin.template:
    src: vector_config.j2
    dest: "{{ vector_config_dir }}/vector.toml"
    mode: '0644'
  notify: Restart vector

- name: Create systemd unit file for vector
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/vector.service
    content: |
      [Unit]
      Description=Vector Service
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/vector --config-toml {{ vector_config_dir }}/vector.toml
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Restart vector

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
